### ISSUE TITLE
Object.getOwnPropertyDescriptors

### ISSUE THREAD

**Issue by zloirock** [hemanth/es7-features#1]
Your example for `Object.getOwnPropertyDescriptor`, not `Object.getOwnPropertyDescriptors`. See [here](https://github.com/zloirock/core-js#ecmascript-7).

**Comment by hemanth** [comment]
@zloirock Thanks for highlighting that, not sure how that got messed! I had read [this](https://gist.github.com/WebReflection/9353781) before creating the repo :)
