### ISSUE TITLE
Object.values/entries are in ES2017

### ISSUE THREAD

**Issue by ljharb** [hemanth/es7-features#14]

**Comment by hemanth** [comment]
@ljharb hmm, so only those in `stage0` shall be `es-next` ?

**Comment by ljharb** [comment]
No, I'm saying that once a proposal is stage 4, it's not "proposed" anymore, it's "in the language".

I think you should keep a list of all post-ES6 things, just put the stage 4 ones in a separate list.

**Comment by hemanth** [comment]
Makes sense, cool, thanks.

**Comment by hemanth** [comment]
I am re-writing the entire repo.
