### ISSUE TITLE
Remove comprehensions

### ISSUE THREAD

**Issue by ljharb** [hemanth/es7-features#2]
The only things officially proposed are at https://github.com/tc39/ecma262/blob/master/stage0.md or https://github.com/tc39/ecma262/ - comprehensions are effectively dead as I understand it, and regardless, they're not on the list.

**Comment by hemanth** [comment]
Both generator and array?

**Comment by ljharb** [comment]
Yes, all

**Comment by hemanth** [comment]
Sad, that array comprehensions was put to sleep.

**Comment by hemanth** [comment]
Thanks for the update :+1:
