### ISSUE TITLE
Why is there already an ES7?

### ISSUE THREAD

**Issue by Toltar** [hemanth/es7-features#5]
I pretty much spent a good couple hours learning ES6 and now their is an ES7?

![Image of Yaktocat](http://memesvault.com/wp-content/uploads/What-Meme-13.jpg)

**Comment by hemanth** [comment]
heh heh :+1:

**Comment by hueitan** [comment]
Awesome :fireworks:

**Comment by Toltar** [comment]
Now a days Javascript has gotten like this:

![actualfeistybettong](https://cloud.githubusercontent.com/assets/6003536/10616164/5074b17a-7729-11e5-896f-2c40d9af7ffc.gif)

I can't keep up :(
