### ISSUE TITLE
lpad

### ISSUE THREAD

**Issue by lvendrame** [hemanth/es7-features#6]
Why is String.prototype.lpad instead String.prototype.padLeft?

**Comment by hemanth** [comment]
//cc @ljharb

**Comment by ljharb** [comment]
Because the old lpad/rpad proposal was abandoned. The [proposal](https://github.com/tc39/proposal-string-pad-left-right) is now `padLeft`/`padRight`.

**Comment by hemanth** [comment]
Thanks :+1:

**Comment by lvendrame** [comment]
You're welcome :+1:
