### ISSUE TITLE
ES7 is out; please update

### ISSUE THREAD

**Issue by rjanardan** [hemanth/es7-features#9]
Thanks for the list. Now that ES7 is out with just exponentiation and Array.prototype.includes(), you may want to update the page.

**Comment by Zorgatone** [comment]
+1 :+1:

**Comment by hemanth** [comment]
I would like to maintain the `stage-0` proposals as well.

**Comment by ljharb** [comment]
Please rename this to "es next" or "ES proposed features" - ES7 is a confusing name.

**Comment by hemanth** [comment]
Ok, will re-name it.

**Comment by RReverser** [comment]
Yeah, `"ES proposed features"` would be much better, as it's not guaranteed that stage-0 features would ever become a standard.

**Comment by ljharb** [comment]
@hemanth it still says "List of ES7 features:"

**Comment by hemanth** [comment]
@ljharb duh! Missed it, done.
